interface AutocompleteOption {
	label: string;
	value: string;
	keywords: string;
}

export const genreOptions: AutocompleteOption[] = [
	{ label: 'Midwest Emo', value: 'Midwest Emo', keywords: 'emo, indie, rock, sad' },
	{ label: 'Shoegaze', value: 'Shoegaze', keywords: 'rock, indie, alternative, psychedelic' },
	{ label: 'Indie Rock', value: 'Indie Rock', keywords: 'rock, indie, alternative' },
	{ label: 'Post Hardcore', value: 'Post Hardcore', keywords: 'rock, indie, sreamo, heavy' },
	{ label: 'Screamo', value: 'Screamo', keywords: 'rock, indie, alternative, heavy' },
	{ label: 'J-Rock', value: 'J-Rock', keywords: 'rock, indie, alternative, japanese' },
	{ label: 'Singer Songwriter', value: 'Singer Songwriter', keywords: 'rock, indie, alternative' },
	{ label: 'Emo', value: 'Emo', keywords: 'rock, indie, alternative' },
	{ label: 'Math Rock', value: 'Math Rock', keywords: 'rock, indie, alternative' },
	{ label: 'Blackgaze', value: 'Blackgaze', keywords: 'shoegaze, alternative, psychedelic, black metal' },
	{ label: 'Post Rock', value: 'Post Rock', keywords: 'rock, alternative' },
	{ label: 'Noise Pop', value: 'Noise Pop', keywords: 'rock, indie, alternative, noise, loud, experimental' },
	{ label: 'Breakcore', value: 'Breakcore', keywords: 'electronic, experimental, noise, loud' },
	{ label: 'Neo-Psychedelia', value: 'Neo-Psychedelia', keywords: 'rock, indie, alternative, psychedelic' },
	{ label: 'Jazz', value: 'Jazz', keywords: 'jazz, experimental, noise, loud' },
]

// const rawGenreList = [
// 	'Midwest Emo',
// 	'Shoegaze',
// 	'Indie Rock',
// 	'Post Hardcore',
// 	'Screamo',
// 	'J-Rock',
// 	'Singer Songwriter',
// 	'Post Rock',
// 	'Emo',
// 	'Indietronica',
// 	'Indie Folk',
// 	'Noise Pop',
// 	'Neo-Psychedelia',
// 	'Math Rock',
// 	'Noise Rock',
// 	'Psychedelic Folk',
// 	'Blackgaze',
// 	'Post Metal',
// 	'Experemental Rock',
// 	'Slowcore',
// 	'Sadcore',
// 	'Folktronica',
// 	'Post-Punk',
// 	'Drone',
// 	'Post-Industrial',
// 	'Gothic Rock',
// 	'Post-Hardcore',
// 	'Spoken Word',
// 	'Poetry',
// 	'Trip Hop',
// 	'Indie Pop',
// 	'Contemporary Folk',
// 	'Americana',
// 	'Pop Punk',
// 	'Advent-Folk',
// 	'Neo-soul',
// 	'Psychedelic Soul',
// 	'Funk',
// 	'Funktronica',
// 	'Acid Jazz',
// 	'Breakcore',
// 	'Atmospheric Drum and Bass',
// 	'Electronic'
// ];

