export const rawGenreList = [
	'Midwest Emo',
	'Shoegaze',
	'Indie Rock',
	'Post Hardcore',
	'Screamo',
	'J-Rock',
	'Singer Songwriter',
	'Post Rock',
	'Emo',
	'Indietronica',
	'Indie Folk',
	'Noise Pop',
	'Neo-Psychedelia',
	'Math Rock',
	'Noise Rock',
	'Psychedelic Folk',
	'Blackgaze',
	'Post Metal',
	'Experemental Rock',
	'Slowcore',
	'Sadcore',
	'Folktronica',
	'Post-Punk',
	'Drone',
	'Post-Industrial',
	'Gothic Rock',
	'Post-Hardcore',
	'Spoken Word',
	'Poetry',
	'Trip Hop',
	'Indie Pop',
	'Contemporary Folk',
	'Americana',
	'Pop Punk',
	'Advent-Folk',
	'Neo-soul',
	'Psychedelic Soul',
	'Funk',
	'Funktronica',
	'Acid Jazz',
	'Breakcore',
	'Atmospheric Drum and Bass',
	'Electronic'
];

